#.travis.yml
language: node_js
node_js:
  - "12.13.0"
branches:
only:
  - main
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - ng build --prod
after_success:
  - ng deploy --token $FIREBASE_TOKEN
notifications:
  email:
  on_failure: change
  on_success: change
