export enum PlaceType {
  Alojamiento = '🛏️ ALOJAMIENTO',
  Ayuntamiento = '🏛️ AYUNTAMIENTO',
  Bar = '🍺 BAR',
  Biblioteca = '📚 BIBLIOTECA',
  Cafeteria = '☕ CAFETERIA',
  Carretera = '🛣️ CARRETERA',
  CentroSalud = '🏥 CENTRO DE SALUD',
  Cine = '🎦 CINE',
  Colegio = '🏫 COLEGIO',
  EspacioDeportivo = '🏟️ ESPACIO DEPORTIVO',
  EspacioNatural = '🏞️ ESPACIO NATURAL',
  EstacionTren = '🚉 ESTACIÓN DE TREN',
  Fabrica = '🏭 FABRICA',
  Iglesia = '⛪ IGLESIA',
  Localidad = '🏘️ LOCALIDAD',
  OtroLugar = '📍 LUGAR',
  Pasteleria = '🍰 PASTELERIA',
  ParadaBus = '🚏 PARADA BUS',
  Plaza = '🎯 PLAZA',
  Puente = '🌉 PUENTE',
  Restaurante = '🍽️ RESTAURANTE',
  Tienda = '🛍️ TIENDA',
  ViviendaPrivada = '🏠 VIVIENDA PRIVADA',
}

const PLACE_TYPES: PlaceType[] = [
  PlaceType.Alojamiento,
  PlaceType.Ayuntamiento,
  PlaceType.Bar,
  PlaceType.Biblioteca,
  PlaceType.Cafeteria,
  PlaceType.CentroSalud,
  PlaceType.Carretera,
  PlaceType.Cine,
  PlaceType.Colegio,
  PlaceType.EspacioDeportivo,
  PlaceType.EspacioNatural,
  PlaceType.EstacionTren,
  PlaceType.Fabrica,
  PlaceType.Iglesia,
  PlaceType.Localidad,
  PlaceType.OtroLugar,
  PlaceType.ParadaBus,
  PlaceType.Plaza,
  PlaceType.Puente,
  PlaceType.Pasteleria,
  PlaceType.Restaurante,
  PlaceType.Tienda,
  PlaceType.ViviendaPrivada,
];

export { PLACE_TYPES };
